-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN "serviceType" TEXT NOT NULL DEFAULT 'REGISTRATION_OFFICE',
ADD COLUMN "serviceRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "travelCosts" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;